# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
  armhf: ghcr.io/home-assistant/armhf-base-debian:bullseye
  armv7: ghcr.io/home-assistant/armv7-base-debian:bullseye
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
  i386: ghcr.io/home-assistant/i386-base-debian:bullseye
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
labels:
  org.opencontainers.image.title: "SMARTBOILER Add-on: SB add-on"
  org.opencontainers.image.description: "SB add-on."
  org.opencontainers.image.source: "https://github.com/grinwi/smartboiler-add-on"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
