# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smart Boiler add-on
version: "0.0.2.10.1.44"
slug: smartboiler
description: Water heating management for Home Assistant with machine learning
url: "https://github.com/grinwi/smartboiler-add-on"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
  - config:rw
image: "ghcr.io/grinwi/image-{arch}-smartboiler-add-on"
hassio_api: true
hassio_role: admin
homeassistant_api: true
host_network: true
environment:
  OPTIONS_PATH: '/data/options.json'
  DATA_PATH: '/data/'
  MODEL_PATH: '/app/lstm_model_zukalovi.h5'
options:

  hass_url: empty
  long_lived_token: empty
  influxdb_host: empty
  influxdb_port: 8086
  influxdb_user: empty
  influxdb_pass: empty
  influxdb_name: empty
  boiler_entidy_id: empty
  boiler_socket_id: empty
  boiler_socket_power_id: empty
  boiler_case_tmp_entity_id: empty
  boiler_case_tmp_measurement: empty
  boiler_water_flow_entity_id: empty
  boiler_water_flow_measurement: empty
  boiler_water_temp_entity_id: empty
  boiler_water_temp_measurement: empty
  boiler_volume: 120
  boiler_set_tmp: 60
  boiler_min_operation_tmp: 37
  average_boiler_surroundings_temp: 20
  boiler_case_max_tmp: 40
  one_shower_volume: 40
  boiler_watt_power: 2000
  household_floor_size: 100
  household_members: 2
  thermostat_entity_id: empty
  logging_level: INFO
  load_model: false
  hdo: false

schema:
  hass_url: str
  long_lived_token: str
  influxdb_host: str
  influxdb_port: int(1,)
  influxdb_user: str
  influxdb_pass: str
  influxdb_name: str
  boiler_entidy_id: str
  boiler_socket_id: str
  boiler_socket_power_id: str
  boiler_case_tmp_entity_id: str
  boiler_case_tmp_measurement: str
  boiler_water_flow_entity_id: str
  boiler_water_flow_measurement: str
  boiler_water_temp_entity_id: str
  boiler_water_temp_measurement: str
  boiler_volume: int(1,)
  boiler_set_tmp: int(1,)
  boiler_min_operation_tmp: int(1,)
  average_boiler_surroundings_temp: int(1,)
  boiler_case_max_tmp: int(1,)
  one_shower_volume: int(1,)
  boiler_watt_power: int(1,)
  household_floor_size: int(1,)
  household_members: int(1,)
  thermostat_entity_id: str
  logging_level: list(DEBUG|INFO|WARNING|ERROR)
  load_model: bool
  hdo: bool
