# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Smart Boiler add-on 2.0
version: "1.2.0.3"
slug: smartboiler
description: Smart Boiler add-on 2.0
url: "https://github.com/grinwi/smartboiler-add-on"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/grinwi/image-{arch}-smartboiler-add-on"
